### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by Jiaheliu137** [facebookresearch/segment-anything-2#41]
Operating Environment:
Windows 11, Python 3.10.14 under Conda.
 I am very sure that all environment variables related to CUDA are set correctly, but I still get an error after running `pip install e .`:

Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      C:\Users\jiahe\AppData\Local\Temp\pip-build-env-zvisi0tm\overlay\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      Traceback (most recent call last):
        File "C:\Users\jiahe\.conda\envs\sam2\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>        
          main()
        File "C:\Users\jiahe\.conda\envs\sam2\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\jiahe\.conda\envs\sam2\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\jiahe\AppData\Local\Temp\pip-build-env-zvisi0tm\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\jiahe\AppData\Local\Temp\pip-build-env-zvisi0tm\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\jiahe\AppData\Local\Temp\pip-build-env-zvisi0tm\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup    
          exec(code, locals())
        File "<string>", line 70, in <module>
        File "<string>", line 51, in get_extensions
        File "C:\Users\jiahe\AppData\Local\Temp\pip-build-env-zvisi0tm\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1076, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "C:\Users\jiahe\AppData\Local\Temp\pip-build-env-zvisi0tm\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1214, in library_paths
          paths.append(_join_cuda_home(lib_dir))
        File "C:\Users\jiahe\AppData\Local\Temp\pip-build-env-zvisi0tm\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by forensicmike** [comment]
same issue, I am using virtualenv. I got passed it once, but decided to clone again fresh and this time I can't get past this step for some reason.

**Comment by 0xIbra** [comment]
https://github.com/facebookresearch/segment-anything-2/issues/19

**Comment by Jiaheliu137** [comment]
> #19

Thank you, but I have already seen this issue and tried pip install --no-build-isolation -e .
I still get the error OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by 0xIbra** [comment]
to build sam2, first you also need to install these (at least for me it was):

```
--extra-index-url https://download.pytorch.org/whl/cu121 # here set your cuda version if it's not 12.1
torch>=2.3.1
torchvision>=0.18.1
transformers
numpy<2
tqdm>=4.66.1
hydra-core>=1.3.2
iopath>=0.1.10
pillow>=9.4.0
wheel
ninja
```

let me know if this helps.

**Comment by jeanchristopheruel** [comment]
> to build sam2, first you also need to install these (at least for me it was):
> 
> ```
> --extra-index-url https://download.pytorch.org/whl/cu121 # here set your cuda version if it's not 12.1
> torch>=2.3.1
> torchvision>=0.18.1
> transformers
> numpy<2
> tqdm>=4.66.1
> hydra-core>=1.3.2
> iopath>=0.1.10
> pillow>=9.4.0
> wheel
> ninja
> ```
> 
> let me know if this helps.

No need to install these explicitly since they are already set as install deps in setup.py. 

Segment Anything 2.0 require to compile a .cu file with nvcc at build time. Hence, a cuda installation is required. You can use a "cuda devel" pytorch docker image if you want to avoid installing cuda on your machine.

**Comment by miketdn** [comment]
I'm experiencing the same problems. I have tried installing different versions of CUDA (12.1, 12.4, 12.5), all with the respective pytorch. Checked that cuda is available (import torch > torch.cuda.is_available() > returns True).

When I run `pip install e .`, I get an error similar to yours, where CUDA_HOME is not set. And when I run `pip install --no-build-isolation -e .` as suggested in other threads, I get "An error happened while installing `SAM 2` in editable mode."

Ran out of things to try.

**Comment by jeanchristopheruel** [comment]
> CUDA_HOME

What is your nvcc version? `nvcc --version`
You might only have CUDA Runtime. You need the CUDA compiler.

**Comment by jeanchristopheruel** [comment]
> I'm experiencing the same problems. I have tried installing different versions of CUDA (12.1, 12.4, 12.5), all with the respective pytorch. Checked that cuda is available (import torch > torch.cuda.is_available() > returns True).
> 
> When I run `pip install e .`, I get an error similar to yours, where CUDA_HOME is not set. And when I run `pip install --no-build-isolation -e .` as suggested in other threads, I get "An error happened while installing `SAM 2` in editable mode."
> 
> Ran out of things to try.

What is your nvcc version? nvcc --version
You might only have CUDA Runtime. You need the CUDA compiler.

**Comment by miketdn** [comment]
> > I'm experiencing the same problems. I have tried installing different versions of CUDA (12.1, 12.4, 12.5), all with the respective pytorch. Checked that cuda is available (import torch > torch.cuda.is_available() > returns True).
> > When I run `pip install e .`, I get an error similar to yours, where CUDA_HOME is not set. And when I run `pip install --no-build-isolation -e .` as suggested in other threads, I get "An error happened while installing `SAM 2` in editable mode."
> > Ran out of things to try.
> 
> What is your nvcc version? `nvcc --version` You might only have CUDA Runtime. You need the CUDA compiler.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

**Comment by Jiaheliu137** [comment]
> > I'm experiencing the same problems. I have tried installing different versions of CUDA (12.1, 12.4, 12.5), all with the respective pytorch. Checked that cuda is available (import torch > torch.cuda.is_available() > returns True).
> > When I run `pip install e .`, I get an error similar to yours, where CUDA_HOME is not set. And when I run `pip install --no-build-isolation -e .` as suggested in other threads, I get "An error happened while installing `SAM 2` in editable mode."
> > Ran out of things to try.
> 
> What is your nvcc version? `nvcc --version` You might only have CUDA Runtime. You need the CUDA compiler.



---

Yes, I also reinstalled the environment and followed the commands provided on the PyTorch official website exactly:

```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
```

Then, I downloaded CUDA Toolkit 12.4 according to the CUDA version specified by PyTorch and updated the CUDA environment variables.

Running `nvcc --version` outputs the following:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```

After that, I confirmed that `torch.cuda.is_available()` indeed returns `true`.

However, when I run `pip install -e .`, it still throws the error:

```
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

---

**Comment by Jiaheliu137** [comment]
> > > I'm experiencing the same problems. I have tried installing different versions of CUDA (12.1, 12.4, 12.5), all with the respective pytorch. Checked that cuda is available (import torch > torch.cuda.is_available() > returns True).
> > > When I run `pip install e .`, I get an error similar to yours, where CUDA_HOME is not set. And when I run `pip install --no-build-isolation -e .` as suggested in other threads, I get "An error happened while installing `SAM 2` in editable mode."
> > > Ran out of things to try.
> > 
> > 
> > What is your nvcc version? `nvcc --version` You might only have CUDA Runtime. You need the CUDA compiler.
> 
> Yes, I also reinstalled the environment and followed the commands provided on the PyTorch official website exactly:
> 
> ```
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
> ```
> 
> Then, I downloaded CUDA Toolkit 12.4 according to the CUDA version specified by PyTorch and updated the CUDA environment variables.
> 
> Running `nvcc --version` outputs the following:
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2024 NVIDIA Corporation
> Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
> Cuda compilation tools, release 12.4, V12.4.99
> Build cuda_12.4.r12.4/compiler.33961263_0
> ```
> 
> After that, I confirmed that `torch.cuda.is_available()` indeed returns `true`.
> 
> However, when I run `pip install -e .`, it still throws the error:
> 
> ```
> OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
> ```

Afterward, I successfully ran the command by following the solution provided in [#19](https://github.com/facebookresearch/segment-anything-2/issues/19): pip install --no-build-isolation -e . 

(win11,conda python 3.10,cuda 12.4,pytorch:pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124)

**Comment by Jiaheliu137** [comment]
Thank you all for your help, the issue has been resolved. Here is the method I used (on Windows 11):

First, download [cuda12.4](https://developer.nvidia.com/cuda-12-4-0-download-archive);

Then:

Add a new entry to the system environment variables, with the name `CUDA_HOME` and the value `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4`;

Final:
```bash
cd \segment-anything-2
conda create -n sam2 python=3.10

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

pip install --no-build-isolation -e .
pip install --no-build-isolation -e ".[demo]"
```

**Comment by Jiaheliu137** [comment]
Thank you all for your help, the issue has been resolved. Here is the method I used (on Windows 11):

First, download [cuda12.4](https://developer.nvidia.com/cuda-12-4-0-download-archive);

Then:

Add a new entry to the system environment variables, with the name `CUDA_HOME` and the value `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4`;

Final:
```bash
cd \segment-anything-2
conda create -n sam2 python=3.10

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

pip install --no-build-isolation -e .
pip install --no-build-isolation -e ".[demo]"
```

**Comment by jack-gits** [comment]
can't segment anything-2  work on server without GPU?

**Comment by forensicmike** [comment]
> Thank you all for your help, the issue has been resolved. Here is the method I used (on Windows 11):
> 
> First, download [cuda12.4](https://developer.nvidia.com/cuda-12-4-0-download-archive);
> 
> Then:
> 
> Add a new entry to the system environment variables, with the name `CUDA_HOME` and the value `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4`;
> 
> Final:
> 
> ```shell
> cd \segment-anything-2
> conda create -n sam2 python=3.10
> 
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
> 
> pip install --no-build-isolation -e .
> pip install --no-build-isolation -e ".[demo]"
> ```

is CUDA 12.4 necessary? Can 12.1 work?

**Comment by 0xIbra** [comment]
> > Thank you all for your help, the issue has been resolved. Here is the method I used (on Windows 11):
> > First, download [cuda12.4](https://developer.nvidia.com/cuda-12-4-0-download-archive);
> > Then:
> > Add a new entry to the system environment variables, with the name `CUDA_HOME` and the value `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4`;
> > Final:
> > ```shell
> > cd \segment-anything-2
> > conda create -n sam2 python=3.10
> > 
> > pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
> > 
> > pip install --no-build-isolation -e .
> > pip install --no-build-isolation -e ".[demo]"
> > ```
> 
> is CUDA 12.4 necessary? Can 12.1 work?

yup, works fine on 12.1.

**Comment by forensicmike** [comment]
Ran into another error: `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.`

(I'm using VS 2022 Preview, which apparently causes this error)
I edited the setup.py to include `-allow-unsupported-compiler` on NVCC and it seems to have finally built. Hopefully I can get it running this time!

**Comment by Windaway** [comment]
> -allow-unsupported-compiler

It works for me. Thx

**Comment by happybear1015** [comment]
棒极了，终于环境问题解决了！！！！

**Comment by M-ael** [comment]
I send this for anyone in the future that encounters the "OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root." while trying to install their own package:

If you see the error happening at "[...]/cpp_extension.py", it might very well be that **the isolated pip environment isn't using the correct version of torch**. If you've pip installed a specific version of torch to your venv _**that is not listed as one of the available versions**_ (you can check the list through "pip index versions torch"), with a url, for example, then **you have to provide that as an argument to the pip install**, and include torch as a dependency (in pyproject.toml as "requires = ["torch==\<yourversion\>"]").
So: "pip install --extra-index-url \<put url here\> . "

_**I recommend this over using the "--no-build-isolation" flag**_, because the build isolation that pip does has a purpose; you don't want to just completely remove it, unless you have your own purpose.
